### ISSUE TITLE
Plane is a common name that causes problems when not in a namespace

### ISSUE THREAD

**Issue by happypwn** [DanniSchou/MeshSplitting#1]
Hi,

Plane is a very common name in Unity and can cause naming collision.

Consider putting the project in its own namespace or changing the Plane name to something different.

**Comment by DanniSchou** [comment]
That's a good point, I'll put it all into it's own namespace to keep it separated.

**Comment by DanniSchou** [comment]
I dropped everything into it's own namespace and changed the Plane class name as well.
This change might cause some merge conflicts but should be fairly easy to solve since no functionality changed.
